task: "train"
log_dir: "logs/train_dl"

training:
  debugging: false
  seed: 42
  epochs: 100
  batch_size: 64
  lr: 0.001
  is_weighted_sampler: true
  early_stop_patience: 15
  monitored_metric: "acc"

data:
  dataset_name: "vr"
  num_samples: null
  anno_dir: "features/groundvqa_qn0"
  anno_train_filename: "annotations.VRbinary_00000_train_close.json"
  anno_val_filename: "annotations.VRbinary_00000_val_close.json"
  anno_test_filename: "annotations.VRbinary_00000_test_close.json"
  n_classes: 2
  cls_type: "binary"
  videodata_dir: "data/videodata_256/clips"
  vrdata_dir: "data/vrdata"
  T: 30
  frame_size: [224, 224]
  crop_anchor: "padding"
  egocentric_only: true
  motion_cols: []
  vel_cols: []
  pose_cols: []
  gaze_cols: []
  goal_cols: []

visual_encoder: "clip"
backbone_models: 
  "pixel":
    backbone_out_dim: 256
    backbone_hidden: 64
  "cnn":
    backbone_out_dim: 256
    backbone_hidden: 64
  "clip":
    backbone_out_dim: 512
    clip_model: "ViT-B/32"
    freeze_clip: true

model_name: "lstm" # "lstm" | "transformer" | "cross_attention"
models:
  lstm:
    d_model: 128
    hidden_dim: 128
    num_layers: 2
  transformer:
    d_model: 128
    nhead: 8
    num_layers: 4
    dim_feedforward: 512
    dropout: 0.0
    max_time_steps: 64
